### ISSUE TITLE
undefined method `merge' for nil:NilClass

### ISSUE THREAD

**Issue by taman9333** [katafrakt/hanami-shrine#10]
I am trying to upload image based on the usage written in the DOCs but it give me the error attached
<img width="1440" alt="Screen Shot 2019-11-05 at 2 52 07 PM" src="https://user-images.githubusercontent.com/29257107/68210717-c980e100-ffde-11e9-898d-ffd2793f706e.png">

**Comment by katafrakt** [comment]
Hi @taman9333!

Can you show how your `Course` looks like? It seems from the error message that it's not a Hanami Entity. Also, which version of Hanami are you using?

**Comment by taman9333** [comment]
Hi @katafrakt 
I've opened a pull request. The problem with me was that bundler install shrine version 3 as in the Gemfile gem 'shrine', '>= 2.7.0'

**Comment by katafrakt** [comment]
Right. That's true, but it has been fixed in 0.4.1 I released few weeks ago. I'm working on support for Shrine 3, but it's a bit more complicated than I expected.

**Comment by katafrakt** [comment]
Fixed by #11
