### ISSUE TITLE
Is hanami-shrine 0.1.0 compatible with hanami 1.3.0?

### ISSUE THREAD

**Issue by tewain** [katafrakt/hanami-shrine#12]
I'm trying to set up hanami-shrine in a project with hanami v. 1.3.0 and I'm getting `LoadError: cannot load such file -- hanami-shrine`. I was wondering if it may be a problem of compatibility or should I be looking for something else?

**Comment by cllns** [comment]
No, I don't think so. Can you use the latest version of `hanami-shrine`? `v0.4.1`

**Comment by katafrakt** [comment]
No, it's guaranteed to not work, as it was compatible with Hanami pre-1.0, where many things were completely different. As @cllns said, please try with latest version of `hanami-shrine`.
