### ISSUE TITLE
Use hanami 1.0

### ISSUE THREAD

**Issue by davydovanton** [katafrakt/hanami-shrine#4]
Hey!
What do you think if we set required hanami version to 1.0?
Also, do you need some help with it?

Thanks!

**Comment by katafrakt** [comment]
Hi @davydovanton! I did some preliminary tests and it seems that current version works just fine with 1.0, so no additional work is necessary (I have to do more tests). What benefit would that be if we require Hanami 1.0 at least?

Of course, I'm not planning to maintain compatibility with old unstable versions on purpose, but right now it seems that there are no breaking changes from 0.9 to 1.0 which would require to drop 0.9 support.

**Comment by katafrakt** [comment]
Support for versions less than 1.0 was dropped in 0.3.0: https://github.com/katafrakt/hanami-shrine/releases/tag/0.3.0
