### ISSUE TITLE
Repository#create does not consistent to original hanami implement

### ISSUE THREAD

**Issue by famano** [katafrakt/hanami-shrine#7]
Hi, I use hanami-shrine in SomeRepository like the following code. 
```ruby
class SomeRepository < Hanami::Repository
  prepend ImageUploader.repository(:image)
end
```
Then, when I call `SomeRepository.create(name: 'some', profile: 'something')`, I got the folloing error.
```
NoMethodError: undefined method `profile_image' for {:name=>'some', :profile=>'something'}:Hash
```

The reason this error occurs is prepended create method only supporting parameter of Entity like this.
```ruby
def create(entity)
  save_attachments(entity) { |new_entity| super(new_entity) }
end
```
Since original hanami supports both Entity and Hash parameter in create method, I consider this behavior as a bug.
So I propose to fix create method to taking Hash parameter and just convert Hash into Entity.

**Comment by katafrakt** [comment]
Hi @famano and thank you for this report.

I fixed this in commit 16ac95899b90536fa35230dd7fb65a973c239a18, can you check it?

I'm not sure about this change though, as it changes what is passed to original repository methods (`Hanami::Shrine` changes hash to entity, there's no really other way to do it, I guess). This should not create any problems for now though.

**Comment by famano** [comment]
@katafrakt Nice work! 
Actually, Original hanami implement of repository#create is just passing over its superclass. So, If this fixation causes problems, studying ROM::Repository will help us.

**Comment by katafrakt** [comment]
I know, I started to use bare ROM recently so I hope to gain more knowledge about it soon.
